site_name: Neural networks from scratch
repo_url: https://github.com/Mikel-MG/neural-networks-from-scratch
nav:
  - Home: index.md
  - Examples:
      - Introduction to gradients: notebooks/0_gradients_prologue.ipynb
  - Math:
      - Activation functions: math_activations.md
      - Loss functions: math_losses.md
  - API reference:
      - Datasets: api/api_datasets.md
      - Model: api/api_model.md
      - Layers: api/api_layers.md
      - Loss functions: api/api_losses.md
      - Activation functions: api/api_activations.md
      - Optimizers: api/api_optimizers.md
theme:
  name: material
  palette:
    # palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: light blue
      accent: cyan
    # palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

  features:
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
              allow_inspection: true
              show_signature_annotations: false
              show_root_heading: false
              show_root_toc_entry: false
              show_source: true
              backlinks: true
              # show_inheritance_diagram: true
              show_submodules: true
              docstring_style: google
              members_order: source
  - mkdocs-jupyter:
      ignore_h1_titles: True


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
